env:
  es6: true
  node: true

globals:
  assert: true
  browser: true
  expect: true

parserOptions:
  ecmaVersion: 6
  sourceType: module

root: true

rules:
  comma-dangle:
    - 'error'
    - arrays: 'always-multiline'
      objects: 'always-multiline'
      exports: 'never'
      functions: 'ignore'
  indent:
    - 'error'
    - 4
    - SwitchCase: 1
  max-len:
    - 'error'
    - 160
    - ignorePattern: '\s*\/\^(.*)\$\/,$'
  new-cap:
    - 'error'
    - newIsCap: true
      capIsNewExceptions:
        - 'Given'
        - 'When'
        - 'Then'
  require-jsdoc:
    - 'error'
    - require:
        FunctionDeclaration: false
        MethodDefinition: false
        ClassDeclaration: false
  strict: 'off'
  valid-jsdoc:
    - 'error'
    - requireReturn: false
      matchDescription: '.+'
